# Practice on NumPy and pandas

Here are some task for you, to refresh what you saw in the notebooks before.

It will help you strengthen the **learning objectives** from the notebook before. You should be able to
- create NumPy arrays
- manipulate them with basic mathematics operators
- extract rows, columns and items by indexing
- use aggregation methods (like sum, min, max, std) on NumPy arrays


## Part 1: Creating NumPy arrays.

1. Please create a NumPy array from the list:
```Python
my_list = [1, 2, 5, 6, 8]
````

- Please create a numpy array containing the values from 1 to 10.
-  Please create a numpy array from 0 to 5 with a step size of 0.2
- Create a numpy array with the shape 2,3 with random values


In [5]:
import numpy as np

my_list = [1, 2, 5, 6, 8]
first_nparry = np.array(my_list)
first_nparry

array([1, 2, 5, 6, 8])

2. Please create a NumPy array containing the values from 1 to 10.


In [13]:
#range_list = list(range(1,11))
#second_array = np.array(list(range(1,11)))
second_array = np.arange(1, 11)
second_array



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Please create a NumPy array from 0 to 5 with a step size of 0.2


In [15]:
third_nparray = np.arange(0, 6, 0.2)
third_nparray

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8])

4. Create a NumPy array with the shape 2,3 with random values


In [16]:
forth_nparray = np.random.rand(2, 3)
forth_nparray

array([[0.77974387, 0.04352221, 0.325026  ],
       [0.30880662, 0.55875203, 0.55170754]])

## Part 2: Manipulate NumPy arrays.

1. Please create a NumPy array with (1, 3, '4', 7, 12, '0'). Define the content as integer.


In [17]:
int_nparray = np.array((1, 3, "4", 7, 12, "0"), np.int16)
int_nparray

array([ 1,  3,  4,  7, 12,  0], dtype=int16)

2. Check the data type of the objects and the shape of the array


In [19]:
int_nparray.dtype

dtype('int16')

In [20]:
int_nparray.shape

(6,)

3. Update the 4th value to 30.


In [21]:
int_nparray[3] = 30
int_nparray

array([ 1,  3,  4, 30, 12,  0], dtype=int16)

4. Reshape the array to a 2x3 matrix.


In [29]:
new_nparray = int_nparray.reshape(2, 3)

new_nparray


array([[ 1,  3,  4],
       [30, 12,  0]], dtype=int16)

5. Please add 8 to each value in the first row and 12 to each in the second row.


In [31]:
new_nparray + [[5], [12]]

array([[ 6,  8,  9],
       [42, 24, 12]])

6. Multiply the first column with 2, the second with 3 and the third with 4.


In [32]:
new_nparray * [2, 3, 4]

array([[ 2,  9, 16],
       [60, 36,  0]])

7. Please sum up all numbers in the first row, and all numbers in the second row.


In [33]:
new_nparray.sum(axis=1)

array([ 8, 42])

8. Similarly, search for the largest number for each column.


In [34]:
new_nparray.max(axis=0)

array([30, 12,  4], dtype=int16)

9. Extract the number in the second column and the first row.


In [35]:
new_nparray[0,1]

np.int16(3)

10. Check at which index the value is exactly 48.

In [37]:
np.where(new_nparray == 30)

(array([1]), array([0]))